### ISSUE TITLE
Dates format in generated files

### ISSUE THREAD

**Issue by BluePiaf** [Karanraj/ExportfromListView#2]
Despite your last comment on "clicksandcode", I can't see a change in Dates formating in the generated files. I deployed the last version of your code, but I still see in generated files :
    <tr> <td>Tue Oct 10 00:00:00 GMT 2006</td>
           <td>Sat Jan 10 00:00:00 GMT 2015</td>
    </tr> 
Not the expected 1/16/2015 9:15 AM date format... Did I miss something ?

**Comment by karanrajs** [comment]
Hi BluePiaf - Now I have pushed the latest code in the github, hope that will resolve the latest change issue. Can you please test and re-confirm again.

**Comment by BluePiaf** [comment]
OK. That's better, thanks. 

However, the US format is far from universal and leads to mistakes in the interpretation of the date. For my test, I had to open back the file three times in order to get de right configuration for the interpretation of the dates in Excel. Well, I am french :-) , working on a spanish-configured computer, migrating old data (Access97 with it own date format) to a new international SF database : dates format are a nightmare for me ! But the only universal format that doesn't leads to mistakes is the YYYY-MM-DD_HH:mm format. Really no way to get the dates formated that way ?

EDIT: I had a look at your code and saw that date format relies on declared locale. It looks like both China (zh-cn ?) and French Canada (fr_CA ?) use YYYY-MM-DD as default date format, and some others too. If there is no "universal locale", that's worth a try, maybe... Cf. http://en.wikipedia.org/wiki/Date_format_by_country

Other small request : would it be possible to keep the "hours:seconds" information of the original date field, too ? I would need it when exporting 'Last modified date' field, for example.

Thank you.

**Comment by karanrajs** [comment]
The problem is we are generating field dynamically from the list view, so it will be some extra work to identify the which field is date/time type and make the date formate as you requested. Some user might want the date view in some other formate, so we need to update the code again and again for that. Once I get some bandwidth will try to change the date formate, without making more change in the code.

As of now, only option is changing the date formate in the excel sheet for your need.

**Comment by BluePiaf** [comment]
Hi, Karanraj. OK, I understand the work that is behind, and that's OK for now, thanks. 

But for archive, for when you will have time to come back on this point, let me explain better: 
- I didn't mean to have a "Excel date-field" in the output. I understand that's a big work. As you say, the date field is exported as basic text, and that's OK for me. I guess you had to "hard-format" the date of the output in order to have a US format. 
- but as it's text, Excel has to interpret the text field _anyway_, whatever the "hard code" format you choose for the date. _Any_ user will have to "format it in the excel sheet for his needs", because Excel asks for it when you open the file. 
- As the "hard output" in US format can lead to mis-interpretation and erroneous data, I guess it is safer - for a text field that has to be interpreted anyway by Excel-, to choose an "universal" "hard-format output", that _can't_ lead to erroneous data.

But for now, you are right : it works, and that's what imported to me. Thanks

**Comment by BluePiaf** [comment]
Hey, Karanraj ! I tried to change the locale in the VF page exportStandardListView (l.1) by fr_CA (French Canada), and that works great !! The date format is YYYY-MM-DD, and the date-time format is YYYY-MM-DD HH:mm exactly as expected ! The exported file is completly fool-proof now with respect to the dates, that's PER-FECT !

**Comment by karanrajs** [comment]
Very glad to know its working for you now. :+1:
