### ISSUE TITLE
Doesn't work with Person Account [solved]

### ISSUE THREAD

**Issue by BluePiaf** [Karanraj/ExportfromListView#3]
Just to put all the issues in one place. :-)

The error message : "A problem with the OnClick JavaScript for this button or link was encountered: listview is undefined"

**Comment by karanrajs** [comment]
Enabled person account in one of my developer org and tested, I'm not facing any issue while exporting from account object. By seeing the error message, I think there is some mistake in the code in the button. Can you please recheck the code in the button.

**Comment by BluePiaf** [comment]
Well, I copy-pasted the code that is on your ExportfromListView GitHub HomePage, I tried many things, I deployed it in another old sandbox... and still the same. I can't figure out what would have my org different than yours, that would lead to error...

Note that in Chromium, the message is different : "Cannot read property 'options' of undefined". Does that give any clue ?

**Comment by BluePiaf** [comment]
I Karanraj ! 

Hope you're well. After all this time, a friend of mine had a look for me at your code and managed to make it work with Person Account. There are the changes to commit :  

**1. In the javascript button**
change: <code>document.getElementsByName('fcf')[0]</code> 
by: <code>document.querySelectorAll('[name$="fcf"]')[0]</code>

expl: in Person Account, listview's name **ends with** 'fcf', but just 'fcf' won't work.

**2. In Apex Class listviewAPI, l.56**

Change: 
<code>String endpointUrl=domainUrl+'/services/data/v32.0/sobjects/'
+ObjectName+'/listviews/'+listid+'/describe';</code>
by: 
<code>String endpointUrl=domainUrl+'/services/data/v32.0/sobjects/'
+(ObjectName=='Person_Account'?'Account':ObjectName)+'/listviews/'+listid+'/describe';</code>

expl: PersonAccount object doesn't have its own listviews, but uses standard Account listviews instead. So we have to change url to standard Account listview if PersonAccount is detected.

Now it works OK for us. Thanks !

**Comment by karanrajs** [comment]
Hi BluePiaf - Thanks for your update. Please feel free to fork this project and push your change/update to this repository.
