### ISSUE TITLE
Request/question: on RelatedLists

### ISSUE THREAD

**Issue by BluePiaf** [Karanraj/ExportfromListView#4]
Hi, Karanraj. I guess RelatedList are based in some way on ListView, too, right ? So maybe just changing the button code parameters would make your script to work for RelatedLists too ? Or is it more complicated ?

For information : if I use my "ExportfromListView" button (that works on a "normal" ListView) on a RelatedList in the Master Object, I receive the error : "A problem with the OnClick JavaScript for this button or link was encountered: listview is undefined"

**Comment by karanrajs** [comment]
We are using salesforce list view API for this functionality. Currently this API is not supported for related list view sections. Check more details here http://releasenotes.docs.salesforce.com/en-us/winter15/release-notes/rn_api_rest.htm
