### ISSUE TITLE
Deployment CompleteCode coverage issue

### ISSUE THREAD

**Issue by BluePiaf** [Karanraj/ExportfromListView#5]
I tried to deploy ExportfromListView on my Production instance, and the GitHub Salesforce Deploy Tool fails with this errors : 
"Deployment CompleteCode coverage issue -- Average test coverage across all Apex Classes and Triggers is 73%, at least 75% test coverage is required."

**Comment by karanrajs** [comment]
Included Apex test classes in the components to resolve code coverage issues.
