### ISSUE TITLE
Format of Date in Excel

### ISSUE THREAD

**Issue by rohasharma23** [Karanraj/ExportfromListView#6]
Hi,
would it be possible to export date fields in a universal way (ex: YYYY-MM-DD_HH:MM:SS) ? My excel output show dates as text fields like "Sat Jan 10 00:00:00 GMT 2015", that I can't convert back to date.

Please tell how to resolve this issue.

thanks 
rohan

**Comment by karanrajs** [comment]
Hi Rohan,

You have to set locale in the visualforce page exportStandardListView. Based on the locale value in visualforce page. The date formate will be exported, check the closed issues list for more details.

Thanks,
Karan
